tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/TestCase/Shell/Task/ProjectTaskTest.php
Get 100% of the tests to actually run :tada:
=> Unskip skipped/incomplete tests.

src/Shell/Task/FixtureTask.php
This little guy slipped through the cracks.
=> Use Text class instead of String

src/Template/Bake/Element/form.ctp
It was painfull to manually add the empty option to the baked views. So I added code that would check the schema and if the field is nullable, the empty option is added.
=> Add empty entry on nullable fields that will render as select inputs

composer.json, src/Template/Bake/Plugin/composer.json.ctp, tests/comparisons/Plugin/SimpleExample/composer.json
cakephp/app requires this, so plugins don't have to.
Depends on cakephp/app#216
=> Remove plugin installer dependency

src/Shell/Task/ControllerTask.php, src/Shell/Task/FixtureTask.php, src/Shell/Task/ModelTask.php, src/Shell/Task/TestTask.php
=> fix issuse #37 

composer.json, src/Shell/Task/ProjectTask.php
There is no restriction on what a project root folder can be named
=> The app folder name is not a namespace

src/Template/Bake/Element/form.ctp
Passed all current tests (11) under /bake
=> - include 'empty' => true, 'default' => '' for date DEFAULT NULL fields

src/Shell/BakeShell.php
=> Add plugin option to `bake all`.

src/Shell/Task/TemplateTask.php
=> Add modelClass to the bake template scope.

src/Shell/Task/ModelTask.php, tests/Fixture/InvitationsFixture.php, tests/TestCase/Shell/Task/ModelTaskTest.php
Re-do the changes from #54 as github can't figure things out anymore, also add tests.
=> Re-implement finding belongsTo using constraints

src/Shell/Task/TemplateTask.php
=> Detailed 'all' as being optional

src/Template/Bake/Model/table.ctp, tests/comparisons/Model/testBakeTableValidation.php
**TL;DR**
[This](http://i.imgur.com/7ZVEuYK.png) to [this](http://i.imgur.com/NlQwEm5.png).
**What?**
This change will break up the validation rules from a single large, visually messy, block of code into lines grouped by field.
**Why?**
Trying to visually see which rules apply to which field was very frustrating, because I'm lazy.
=> Validation rule code formatting

src/Shell/Task/ControllerTask.php, tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/TestCase/Shell/Task/TestTaskTest.php, tests/comparisons/Controller/testBakeWithPlugin.php, tests/test_app/Plugin/BakeTest/src/Model/Table/BakeArticlesTable.php
Add missing plugin name when getting table object for a name.
Refs #57
=> Fix issue where plugin controllers were missing associations.

src/Template/Bake/Element/Controller/add.ctp, src/Template/Bake/Element/Controller/delete.ctp, src/Template/Bake/Element/Controller/edit.ctp, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php
=> Wrapped baked flash messages with i18n function. Closes #88

src/Shell/Task/ShellHelperTask.php, src/Shell/Task/TestTask.php, src/Template/Bake/Shell/helper.ctp, tests/TestCase/Shell/BakeShellTest.php, tests/TestCase/Shell/Task/SimpleBakeTaskTest.php, tests/TestCase/Shell/Task/TestTaskTest.php
With Shell Helpers mostly complete, I thought it would be good to have bake tasks for them as well.
=> Add Bake task for shell helpers

src/Template/Bake/Model/table.ctp, tests/comparisons/Model/testBakeTableRelations.php
=> Add type hints for associated tables.

src/Shell/Task/FormTask.php, src/Shell/Task/TestTask.php, src/Template/Bake/Form/form.ctp, tests/TestCase/Shell/BakeShellTest.php, tests/TestCase/Shell/Task/SimpleBakeTaskTest.php, tests/TestCase/Shell/Task/TestTaskTest.php
and tests
(we should create milestone for 1.0.9)
=> Add possibility to bake modeless form

src/Shell/BakeShell.php
=> Add force option to `bake all`.

composer.json, tests/TestCase/Shell/BakeShellTest.php
And instead, assert the text looks like the output.
Depends upon https://github.com/cakephp/cakephp/pull/6694
=> Get rid of expects(big number)

composer.json, src/Shell/BakeShell.php, src/Shell/Task/FormTask.php, src/Shell/Task/TestTask.php, src/Template/Bake/Form/form.ctp, src/Template/Bake/Model/table.ctp, tests/TestCase/Shell/BakeShellTest.php, tests/TestCase/Shell/Task/SimpleBakeTaskTest.php, tests/TestCase/Shell/Task/TestTaskTest.php, tests/comparisons/Model/testBakeTableRelations.php
I've merged latest changes from master and added a commit to add the missing bake help option.
=> 1.1 - add missing bake test shell_helper

src/Shell/Task/ModelTask.php
Note that because of how the built-in `validateUnique` method works, we cannot attach this validation rule to multiple fields.
Refs cakephp/bake#34
> Making this PR here as I don't have a way to run tests atm.
=> Add unique validation rule to fields which have a unique constraint

src/Template/Bake/Element/form.ctp, src/Template/Bake/Template/index.ctp, src/Template/Bake/Template/view.ctp, tests/comparisons/Template/testBakeEdit.ctp, tests/comparisons/Template/testBakeIndex.ctp, tests/comparisons/Template/testBakeTemplate.ctp, tests/comparisons/Template/testGetContent.ctp, tests/comparisons/Template/testGetContentAssociations.ctp, tests/comparisons/Template/testGetContentWithRoutingPrefix-add.ctp, tests/comparisons/Template/testGetContentWithRoutingPrefix-view.ctp
We can get the same CSS to apply with classnames. This will match up with a pull request in cakephp/app
=> Don't use common id selectors.

tests/Fixture/InvitationsFixture.php, tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/TestCase/Shell/Task/ModelTaskTest.php
Update tests and fixtures. I hope that this solves the failing tests in AppVeyor as local tests passed against SQLServer 2008.
=> Try and get AppVeyor passing

src/Template/Bake/Plugin/config/routes.php.ctp, src/Template/Bake/config/routes.ctp, tests/comparisons/Plugin/SimpleExample/config/routes.php
=> Use dashedroute by default.

src/Template/Bake/Element/form.ctp
Changed a missed array() into []
=> Make array notation consistant

composer.json, src/Shell/Task/MailerTask.php, src/Template/Bake/Mailer/mailer.ctp, tests/TestCase/Shell/BakeShellTest.php, tests/TestCase/Shell/Task/MailerTaskTest.php, tests/comparisons/Mailer/testBakePlugin.php
This re-applies #77 to the 1.1 branch.
=> 1.1 mailer

src/Shell/Task/PluginTask.php, src/Template/Bake/Plugin/README.md.ctp, src/Template/Bake/Plugin/composer.json.ctp, src/Template/Bake/Plugin/src/Controller/AppController.php.ctp, tests/TestCase/Shell/Task/PluginTaskTest.php, tests/comparisons/Plugin/Company/Example/README.md, tests/comparisons/Plugin/Company/Example/composer.json, tests/comparisons/Plugin/Company/Example/config/routes.php, tests/comparisons/Plugin/Company/Example/phpunit.xml.dist, tests/comparisons/Plugin/Company/Example/src/Controller/AppController.php, tests/comparisons/Plugin/Company/Example/tests/bootstrap.php
Add additional template variables and templates to handle vendor plugins correctly.
Refs cakephp/cakephp#7062
=> Correct plugin generation for vendored plugins.

src/Template/Bake/Model/entity.ctp, tests/comparisons/Model/testBakeEntityFields.php
A middle ground for https://github.com/cakephp/bake/pull/134.
=> Add security note about entity mass assignment bake default

src/Template/Bake/Model/table.ctp, tests/comparisons/Model/testBakeTableConfig.php, tests/comparisons/Model/testBakeTableRelations.php
I think it is far easier to read with a visual break between the table setup, behaviour and associations.
=> Visual break for behaviours

src/View/BakeView.php
=> Write bake's intermediary files inside "bake" subfolder.

src/Shell/Task/ModelTask.php, src/Template/Bake/Model/entity.ctp, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/comparisons/Model/testBakeEntityFieldsDefaults.php, tests/comparisons/Model/testBakeEntityFieldsWhiteList.php, tests/comparisons/Model/testBakeEntityNoFields.php
=> Resurrect field options.

src/Template/Bake/Element/Controller/delete.ctp, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php
The delete() returns \Cake\Network\Response object or null.
=> Fix docblock

src/Shell/BakeShell.php
All() method returns true (correct shell usage and execution) or false (wrong shell usage)
=> block doc return type

src/Shell/Task/BakeTask.php, src/Shell/Task/ControllerTask.php, src/Shell/Task/TemplateTask.php, tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/TestCase/Shell/Task/TemplateTaskTest.php, tests/test_app/App/Controller/Admin/Management/PostsController.php
Addresses how nested prefixes are handled in controller and template generation.
Refs #177
=> Fix nested prefix handling

src/Shell/Task/ControllerTask.php, tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/comparisons/Controller/testBakeActionsOption.php
This allows people to add/remove actions to controller through a CLI
flag. This helps people extend bake or make readonly controllers.
Refs #188
Refs #164
=> Add option to selectively bake actions.

.travis.yml, phpunit.xml.dist, src/Shell/Task/ModelTask.php, tests/TestCase/Shell/Task/ModelTaskTest.php
=> Fix prefixes being applied to models.

src/Shell/Task/FixtureTask.php, tests/TestCase/Shell/Task/FixtureTaskTest.php
=> Add missing types to fixture record generation.

src/Template/Bake/Element/form.ctp
Completes https://github.com/cakephp/bake/pull/48
=> Also respect empty preselect for datetime and time

src/Shell/Task/ModelTask.php, src/Template/Bake/Element/Controller/index.ctp, src/Template/Bake/Element/Controller/view.ctp, src/Template/Bake/Element/form.ctp, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeActionsOption.php, tests/comparisons/Controller/testBakeWithPlugin.php, tests/test_app/Plugin/BakeTest/src/Model/Table/BakeArticlesTable.php
Makes debugging it easier.
Like debug($....);die(); etc.
=> Save to own variable first

src/Shell/Task/TemplateTask.php, src/Template/Bake/Template/index.ctp, tests/TestCase/Shell/Task/TemplateTaskTest.php, tests/comparisons/Template/testBakeIndexWithIndexLimit.ctp
As discussed in #65, this PR implements a flag to set the index number limitation to any value while keeping the default value of 7. 
I would welcome any feedback regarding the implementation + tests, I am uncertain whether its the "best practice".
=> Implementation of Index Column Limitation (Closes #65)

src/Shell/Task/ModelTask.php
Treat timestamp columns like datetime columns for postgres.
=> Fix tests failing on postgres.

tests/TestCase/Shell/Task/ModelTaskTest.php
See: https://ci.appveyor.com/project/cakephp/bake/build/1.0.307#L287
=> Use DS constant for windows

src/Shell/Task/TaskTask.php, src/Shell/Task/TestTask.php, src/Template/Bake/Shell/task.ctp, tests/TestCase/Shell/BakeShellTest.php, tests/TestCase/Shell/Task/SimpleBakeTaskTest.php, tests/TestCase/Shell/Task/TaskTaskTest.php, tests/TestCase/Shell/Task/TestTaskTest.php, tests/comparisons/Shell/Task/testBake.php, tests/comparisons/Shell/Task/testBakePlugin.php, tests/comparisons/Test/testBakeShellTaskTest.php
I was surprised to see that it was not possible to bake a Shell Task class.
This PR implements it.
=> Implements Shell Task baking

src/Shell/Task/ModelTask.php, src/Template/Bake/Plugin/config/routes.php.ctp, tests/comparisons/Plugin/Company/Example/config/routes.php, tests/comparisons/Plugin/SimpleExample/config/routes.php
Adds param type for routes.
Makes the bake consistent with the app template.
https://github.com/cakephp/app/blob/master/config/routes.php
=> Add parameter type

src/Shell/Task/ControllerTask.php, src/Shell/Task/TemplateTask.php, src/Shell/Task/TestTask.php
=> Uses the --connection parameter to create Table object.

src/Template/Bake/Form/form.ctp
=> Add missing @param annotation to form template

.gitattributes
=> Removed tests (except for fixtures) from `git archive`

composer.json, src/Shell/BakeShell.php, tests/TestCase/Shell/BakeShellTest.php, tests/test_app/Plugin/PastryTest/src/Shell/Task/ApplePieTask.php
=> Allows vendored plugins to have bake tasks available

src/Template/Bake/Template/index.ctp, src/Template/Bake/Template/view.ctp, tests/comparisons/Template/testBakeIndex.ctp, tests/comparisons/Template/testBakeIndexWithIndexLimit.ctp, tests/comparisons/Template/testBakeView.ctp, tests/comparisons/Template/testGetContent.ctp, tests/comparisons/Template/testGetContentAssociations.ctp, tests/comparisons/Template/testGetContentWithRoutingPrefix-view.ctp
Hello
Web accessibility is important, so today i add a scope attribute to genrated table.
http://webaim.org/techniques/tables/data
Thanks in advance.
=> Accessibility

src/Template/Bake/Plugin/config/routes.php.ctp
https://github.com/cakephp/docs/pull/4290
=> DashedRoute::class

src/Shell/Task/ModelTask.php, src/Shell/Task/TestTask.php, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/TestCase/Shell/Task/TestTaskTest.php, tests/comparisons/Test/testBakePrefixControllerTestWithCliOption.php
Fix a few problems that have been in the issue queue for a while.
* #236 
* #254
* #267 
Each issue has been fixed with a single commit and the messages have my rationale in them :smile:
=> Fix a few defects

src/Template/Bake/Template/index.ctp
Resolves the issues mentioned https://github.com/cakephp/app/issues/437
=> Add better template defaults.

src/Shell/Task/ControllerTask.php, src/Shell/Task/FixtureTask.php, src/Shell/Task/ModelTask.php, src/Shell/Task/TemplateTask.php, tests/TestCase/Shell/Task/PluginTaskTest.php, tests/comparisons/Template/testBakeIndex.ctp, tests/comparisons/Template/testBakeIndexWithIndexLimit.ctp
Attempt to solve #287 via better help messages instead of interactive prompts when the user may have made a mistake.
I've also fixed up the tests that were failing for me locally.
=> Better help & Fixing tests

src/Shell/Task/ControllerTask.php, src/Shell/Task/PluginTask.php, src/Shell/Task/SimpleBakeTask.php, src/Shell/Task/TemplateTask.php, src/Shell/Task/TestTask.php, src/Template/Bake/Element/Controller/add.ctp, src/Template/Bake/Element/Controller/edit.ctp, src/Template/Bake/Element/Controller/login.ctp, src/Template/Bake/Shell/shell.ctp, src/Template/Bake/Shell/task.ctp, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php, tests/comparisons/Shell/Task/testBake.php, tests/comparisons/Shell/Task/testBakePlugin.php
Resolves https://github.com/cakephp/bake/issues/295 documentation part.
Also cleanup up some warnings about not properly working with void vs null.
=> Fix doc blocks and remove not necessary else.

src/Shell/Task/PluginTask.php, src/Template/Bake/Plugin/src/Controller/AppController.php.ctp
=> Use the App.namespace to load the AppController of the project.

.travis.yml, README.md, appveyor.yml, composer.json, src/Template/Bake/Element/Controller/add.ctp, src/Template/Bake/Element/Controller/edit.ctp, src/Template/Bake/Element/form.ctp, src/Template/Bake/Model/table.ctp, tests/TestCase/Shell/Task/PluginTaskTest.php, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php, tests/comparisons/Model/testBakeTableConfig.php, tests/comparisons/Model/testBakeTableRelations.php, tests/comparisons/Model/testBakeTableValidation.php, tests/comparisons/Model/testBakeTableWithPlugin.php, tests/comparisons/Model/testBakeWithRules.php, tests/comparisons/Template/testBakeEdit.ctp, tests/comparisons/Template/testGetContentWithRoutingPrefix-add.ctp
Update bake to use un-deprecated methods that were added in 3.4.0
Refs #294 #310
=> Update bake for 3.4 deprecations

src/Shell/BakeShell.php, src/Shell/Task/ControllerTask.php, src/Shell/Task/FixtureTask.php, src/Shell/Task/ModelTask.php, src/Shell/Task/PluginTask.php, src/Shell/Task/SimpleBakeTask.php, src/Shell/Task/TemplateTask.php, src/Shell/Task/TestTask.php, src/Template/Bake/Template/login.ctp, tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/comparisons/Controller/testBakeActionsOption.php
Also remove description() and epilog() usage in shell tasks
=> 3.4 deprecations - Remove Form::input generation

src/Shell/BakeShell.php, src/Shell/Task/BakeTask.php, src/Shell/Task/ModelTask.php, tests/TestCase/Shell/Task/ModelTaskTest.php
This finishes https://github.com/cakephp/bake/pull/302 by adding a test case.
=> Adding table prefix handling

tests/TestCase/Shell/Task/MailerTaskTest.php, tests/TestCase/Shell/Task/TestTaskTest.php
=> Remove double blank lines

src/Shell/Task/PluginTask.php
=> Don't escape unicode characters.

src/View/Helper/DocBlockHelper.php
=> Use correct class when annotating entities' datetime properties.

src/Shell/Task/TestTask.php, src/Template/Bake/Element/Controller/add.ctp, src/Template/Bake/Element/Controller/delete.ctp, src/Template/Bake/Element/Controller/edit.ctp, src/Template/Bake/Element/Controller/index.ctp, src/Template/Bake/Element/Controller/login.ctp, src/Template/Bake/Element/Controller/logout.ctp, src/Template/Bake/Element/Controller/view.ctp, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeActionsOption.php, tests/comparisons/Controller/testBakeWithPlugin.php, tests/comparisons/Test/testBakeCellTest.php
For current 3.4 code generation.
=> Use \Cake\Http\Response in doc blocks.

src/Shell/BakeShell.php
=> fix: Run each bake “task” separately to avoid issues when using autotables

src/Shell/Task/ControllerTask.php, src/Template/Bake/Controller/controller.ctp, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php
=> feat: Add pagination annotation to baked controllers

src/Shell/Task/TestTask.php, tests/TestCase/Shell/Task/TestTaskTest.php, tests/comparisons/Test/testBakeFixturesParam.php, tests/comparisons/Test/testBakeModelTest.php, tests/comparisons/Test/testBakeNoFixtureParam.php
=> Use PHP5.5 for test class generation

src/Shell/Task/TemplateTask.php, src/Template/Bake/Template/index.ctp, src/Template/Bake/Template/view.ctp, tests/TestCase/Shell/Task/TemplateTaskTest.php, tests/comparisons/Template/testBakeIndex.ctp, tests/comparisons/Template/testBakeIndexWithIndexLimit.ctp, tests/comparisons/Template/testBakeView.ctp, tests/comparisons/Template/testGetContent.ctp, tests/comparisons/Template/testGetContentAssociations.ctp, tests/comparisons/Template/testGetContentWithRoutingPrefix-view.ctp
=> Additional typehinting for baked templates

src/Shell/Task/FixtureTask.php, src/Template/Bake/Template/index.ctp, src/Template/Bake/Template/view.ctp, src/View/Helper/DocBlockHelper.php, tests/Fixture/DatatypesFixture.php, tests/TestCase/Shell/Task/FixtureTaskTest.php
=> feat: Update fixture generation for small/tiny integers

src/Shell/Task/ControllerTask.php, src/Template/Bake/Controller/controller.ctp, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeActionsOption.php, tests/comparisons/Controller/testBakeComponents.php, tests/comparisons/Controller/testBakeNoActions.php
=> Do not add a '@property Table' annotation if the table does not exist.

src/Shell/Task/ModelTask.php, src/Template/Bake/Model/table.ctp, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php, tests/comparisons/Model/testBakeTableRelations.php
=> Add support for association target class annotations.

src/Template/Bake/Element/Controller/index.ctp, src/Template/Bake/Element/Controller/view.ctp, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php
That code-sniffer fusses at me when I bake a new controller!
Command used:
`phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests`
```
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
17 | WARNING | Function return type is not void, but function has no
|         | return statement
34 | WARNING | Function return type is not void, but function has no
|         | return statement
----------------------------------------------------------------------
```
=> Index & view modified to comply w/ doc blocks.

composer.json, src/Template/Bake/Plugin/composer.json.ctp, tests/comparisons/Plugin/Company/Example/composer.json, tests/comparisons/Plugin/SimpleExample/composer.json
Closes https://github.com/cakephp/bake/issues/348
=> Add MIT as default license

src/Shell/Task/TemplateTask.php, src/Template/Bake/Template/index.ctp, src/Template/Bake/Template/view.ctp, tests/TestCase/Shell/Task/TemplateTaskTest.php, tests/comparisons/Template/testBakeIndex.ctp, tests/comparisons/Template/testBakeIndexWithIndexLimit.ctp, tests/comparisons/Template/testBakeView.ctp
=> Add typehints only if Entity class exist

src/Shell/Task/ModelTask.php, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php, tests/comparisons/Model/testBakeTableValidation.php
Refs cakephp/cakephp#10952. 
Also I removed several deprecated method calls.
=> Use scalar validation for stirng/text columns by default

src/Template/Bake/Template/add.ctp, src/Template/Bake/Template/edit.ctp, src/Template/Bake/Template/index.ctp, src/Template/Bake/Template/login.ctp, src/Template/Bake/Template/view.ctp, tests/comparisons/Template/testBakeEdit.ctp, tests/comparisons/Template/testBakeIndex.ctp, tests/comparisons/Template/testBakeIndexWithIndexLimit.ctp, tests/comparisons/Template/testBakeView.ctp, tests/comparisons/Template/testGetContent.ctp, tests/comparisons/Template/testGetContentAssociations.ctp, tests/comparisons/Template/testGetContentWithRoutingPrefix-add.ctp, tests/comparisons/Template/testGetContentWithRoutingPrefix-view.ctp
Adds on https://github.com/cakephp/bake/commit/870eef65d0f07ce09691b90bc6e496b9793fec87#diff-a626ea56322d5926d35297276402bb3b to have correct indentation
=> Fix indentation for annotation doc blocks

src/Shell/Task/BakeTask.php
All other tasks inherit from BakeTask and get their default params from it.
Refs #365.
=> Set default theme in BakeTask.

src/Shell/BakeShell.php, src/Shell/CommonOptionsTrait.php, src/Shell/Task/BakeTask.php
=> Move common options setting into a trait.

src/Shell/Task/TestTask.php, tests/TestCase/Shell/Task/TestTaskTest.php
=> Fix task tests not working

.gitignore, src/Template/Bake/Controller/controller.twig, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php
Resolves https://github.com/cakephp/bake/issues/398
Also already fixed for IdeHelper in https://github.com/dereuromark/cakephp-ide-helper/pull/71
=> Add missing ResultSetInterface to pagination collections

src/View/Helper/DocBlockHelper.php, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/comparisons/Model/testBakeEntityWithPropertyTypeHints.php
=> Proper annotations for array & json-type fields in entities

tests/TestCase/Shell/Task/CellTaskTest.php, tests/TestCase/Shell/Task/FixtureTaskTest.php, tests/TestCase/Shell/Task/MailerTaskTest.php, tests/TestCase/Shell/Task/MiddlewareTaskTest.php, tests/TestCase/TestCase.php
Move more tests to console integration tests.
=> Update more tests to use integration style tests

phpstan.neon, tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/TestCase/Shell/Task/TestTaskTest.php, tests/test_app/App/Model/Table/BakeArticlesTable.php
Use integration test case where possible.
=> Update controller task tests

src/Template/Bake/View/cell.twig, tests/comparisons/Cell/testBakePlugin.php
=> Add Cell::initialize() to generated code.

src/Template/Bake/Shell/task.twig, tests/comparisons/Shell/Task/testBake.php, tests/comparisons/Shell/Task/testBakePlugin.php
=> Adding getOptionParser method to the shell task

src/Template/Bake/tests/test_case.twig, tests/comparisons/Test/testBakeShellTest.php
Follow https://book.cakephp.org/3.0/en/development/testing.html#console-integration-testing
=> baked shell test case superclass to ConsoleIntegrationTestCase

src/Template/Bake/Plugin/phpunit.xml.dist.twig, tests/comparisons/Plugin/Company/Example/phpunit.xml.dist, tests/comparisons/Plugin/SimpleExample/phpunit.xml.dist
=> Fix up name to make it usable

composer.json, src/Shell/Task/ModelTask.php, tests/TestCase/Shell/BakeShellTest.php, tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/TestCase/Shell/Task/ModelTaskAssociationDetectionTest.php, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/TestCase/Shell/Task/TaskTaskTest.php, tests/TestCase/Shell/Task/TemplateTaskTest.php
This should get tests passing against 3.6.0-beta
=> 3.next - update for deprecations

src/Shell/Task/PluginTask.php, src/Template/Bake/Plugin/composer.json.twig, tests/TestCase/Shell/Task/PluginTaskTest.php, tests/comparisons/Plugin/Company/Example/composer.json, tests/comparisons/Plugin/SimpleExample/composer.json
Consolidate with current cakephp/app skeleton.
=> Fix up plugin baking autoload paths and update to 3.5 core.

src/Plugin.php, tests/TestCase/PluginTest.php
This enables usage with `Application::addPlugin()`
=> Add plugin class for bake.

src/View/Helper/DocBlockHelper.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php, tests/comparisons/Model/testBakeEntityWithPlugin.php, tests/comparisons/Model/testBakeTableConfig.php, tests/comparisons/Model/testBakeTableRelations.php, tests/comparisons/Model/testBakeTableValidation.php, tests/comparisons/Model/testBakeTableWithPlugin.php, tests/comparisons/Model/testBakeWithRules.php, tests/comparisons/Model/testGetBehaviors.php
=> Add saveOrFail() annotation

src/Template/Bake/tests/test_case.twig, tests/TestCase/Shell/BakeShellTest.php, tests/TestCase/Shell/Task/ControllerTaskTest.php, tests/TestCase/TestCase.php, tests/comparisons/Test/testBakeControllerTest.php, tests/comparisons/Test/testBakePrefixControllerTest.php, tests/comparisons/Test/testBakePrefixControllerTestWithCliOption.php, tests/comparisons/Test/testBakeShellTest.php
Follows https://github.com/cakephp/cakephp/pull/12072
=> Updated bake files to use test traits

src/Shell/Task/TestTask.php, tests/comparisons/Test/testBakeShellTaskTest.php
We should not be mocking the entire shell class for tasks.
Refs #459
=> Generate task tests correctly.

src/Shell/Task/ModelTask.php, tests/Fixture/BakeArticlesFixture.php, tests/Fixture/CategoryThreadsFixture.php, tests/Fixture/NumberTreesFixture.php, tests/TestCase/Shell/Task/ModelTaskAssociationDetectionTest.php, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTableSigned.php, tests/comparisons/Model/testBakeEntityFieldsWhiteList.php, tests/comparisons/Model/testBakeEntityNoFields.php, tests/comparisons/Model/testBakeEntityWithPropertyTypeHints.php, tests/comparisons/Model/testBakeTableValidation.php
Unsigned Integer columns use "NonNegativeInteger" validation instead of a plain "Integer" validation.
For numeric and decimal columns "comparison" validator will be used. It will ensure that entered values are greater than zero.
Refs #439
=> Validation for unsigned integer columns

src/Template/Bake/Element/Controller/edit.twig, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php
alternative to : https://github.com/cakephp/bake/pull/473
=> Fixes #462 Wrong Exception

.travis.yml, src/Command/PluginCommand.php, src/Plugin.php, src/Utility/Process.php, tests/TestCase/Command/PluginCommandTest.php, tests/TestCase/Shell/BakeShellTest.php, tests/comparisons/Plugin/Company/Example/src/Controller/AppController.php, tests/comparisons/Plugin/SimpleExample/src/Controller/AppController.php
I've created another utility class for subprocess calls so that we don't end up with another big base class that is a kitchen sink of features.
=> Move PluginTask to a command

src/Command/ControllerCommand.php, src/Plugin.php, tests/TestCase/Command/ControllerCommandTest.php, tests/TestCase/Shell/BakeShellTest.php, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeActionsOption.php, tests/comparisons/Controller/testBakeComponents.php, tests/comparisons/Controller/testBakeNoActions.php
I'll add `controller all` separately. For now its tests are skipped.
=> Convert controller task to a command.

src/Command/ControllerAllCommand.php, src/Plugin.php, tests/TestCase/Command/ControllerAllCommandTest.php, tests/TestCase/Command/ControllerCommandTest.php
Also fix a few other small mistakes I made.
=> 4.x - Add controller all command.

.gitignore, composer.json, phpcs.xml.dist
with some convenient functions
=> Add Composer scripts

src/View/Helper/DocBlockHelper.php
BC break ( https://github.com/cakephp/bake/pull/509/files#diff-9e729c6fd0a87c9303d114549f819a45R34 ) fixed
See https://travis-ci.org/dereuromark/cakephp-ide-helper/jobs/511918535
=> Fix regression in previous patch

src/Shell/Task/ModelTask.php, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTableSigned.php
=> Use new notEmpty* validator methods.

src/Shell/Task/PluginTask.php
Little update for PluginTask to get rid of deprecated `Plugin::load`
=> Use cakephp to load plugin

tests/comparisons/Model/testBakeAssociationDetectionCategoriesTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTableSigned.php
https://github.com/cakephp/bake/pull/521#issuecomment-483700196
=> saveOrFail return type

src/View/Helper/DocBlockHelper.php, tests/TestCase/View/Helper/DocBlockHelperTest.php
As asked by @dereuromark at https://github.com/cakephp/bake/pull/514#issuecomment-477235431
Sorry for sneaking in some unrelated improvements.
Hope they are fine, too.
Didn't have time to cover all methods, though. :sleeping_bed:
=> DocBlockHelper Regression Test

templates/bake/element/Controller/add.twig, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php
=> Use new method for new empty entity.

templates/bake/tests/fixture.twig, tests/comparisons/Fixture/testImportRecordsFromDatabase.php
Added the correct method return type, to fix a mismatched method signature
Apologies for not creating a topic branch!
=> Resolves #522 - Correct fixture init method signature

src/Command/PluginCommand.php, templates/bake/Plugin/composer.json.twig, tests/TestCase/Command/PluginCommandTest.php, tests/test_app/composer.json
=> Use app's cakephp version in composer.json of plugins.

src/View/Helper/DocBlockHelper.php, tests/comparisons/Model/testBakeEntityFieldsDefaults.php, tests/comparisons/Model/testBakeEntityFieldsWhiteList.php, tests/comparisons/Model/testBakeEntityNoFields.php, tests/comparisons/Model/testBakeEntityWithPropertyTypeHints.php
=> Typehint properties for decimal fields as string instead of float.

src/View/BakeView.php
=> changed _getViewFileName() to _getTemplateFileName()

.travis.yml, composer.json, src/Command/FixtureCommand.php, src/Command/ModelCommand.php, src/Command/TemplateCommand.php, src/Command/TestCommand.php, src/Shell/Task/TemplateTask.php, src/Utility/Model/AssociationFilter.php, src/Utility/SubsetSchemaCollection.php, src/Utility/TableScanner.php, src/View/BakeView.php, src/View/Helper/BakeHelper.php, src/View/Helper/DocBlockHelper.php
and made docblocks more strict
We might also want to look into level 5 phpstan issues, as they are valid:
```
------ ------------------------------------------------------------------------- 
Line   Command/AllCommand.php                                                   
------ ------------------------------------------------------------------------- 
70     Parameter #1 $connection of class Bake\Utility\TableScanner constructor  
expects Cake\Database\Connection, Cake\Datasource\ConnectionInterface    
given.                                                                   
------ ------------------------------------------------------------------------- 
------ ------------------------------------------------------------------------- 
Line   Command/ControllerAllCommand.php …
```
=> Fix signatures to remove type errors

.travis.yml, src/Template/Bake/Plugin/tests/bootstrap.php.twig, tests/bootstrap.php, tests/comparisons/Plugin/Company/Example/tests/bootstrap.php, tests/comparisons/Plugin/SimpleExample/tests/bootstrap.php
Ensure that autoloader and loadPhpunitAliases() are loaded.
Fixes #559
=> Fix plugin bootstrap generation

src/Shell/Task/ModelTask.php, tests/TestCase/Shell/Task/ModelTaskTest.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTableSigned.php
=> Update argument order for "allowEmpty" validation methods.

src/View/Helper/DocBlockHelper.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php, tests/comparisons/Model/testBakeAssociationDetectionCategoriesTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionOldProductsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTableSigned.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php, tests/comparisons/Model/testBakeAssociationDetectionProductsTableSigned.php, tests/comparisons/Model/testBakeEntityWithPlugin.php, tests/comparisons/Model/testBakeTableConfig.php, tests/comparisons/Model/testBakeTableRelations.php, tests/comparisons/Model/testBakeTableValidation.php, tests/comparisons/Model/testBakeTableWithPlugin.php, tests/comparisons/Model/testBakeWithRules.php, tests/comparisons/Model/testGetBehaviors.php
Closes #573 
Also [Table::save()](https://api.cakephp.org/3.8/class-Cake.ORM.Table.html#_save) returns false instead of bool
=> Use Class Intersection in Associations

src/Template/Bake/tests/test_case.twig, tests/comparisons/Test/testBakeCommandTest.php, tests/comparisons/Test/testBakeControllerTest.php, tests/comparisons/Test/testBakePrefixControllerTest.php, tests/comparisons/Test/testBakePrefixControllerTestWithCliOption.php
Resolves https://github.com/cakephp/bake/issues/577
=> Add uses annotations for magically/indirectly invoked test classes.

templates/bake/Template/index.twig, templates/bake/Template/view.twig, tests/comparisons/Template/testBakeIndex.php, tests/comparisons/Template/testBakeIndexWithIndexLimit.php, tests/comparisons/Template/testBakeView.php
=> Fix tables overflowing out of container.

src/Command/ModelCommand.php, src/Command/TemplateCommand.php, src/View/Helper/BakeHelper.php, src/View/Helper/DocBlockHelper.php, tests/TestCase/Shell/Task/SimpleBakeTaskTest.php
* Fix warning for missing delete template (it isn't actually missing)
* Fix failing tests.
* Apply latest PHPCS rules.
=> Fix warning about missing delete template

src/Command/CellCommand.php, tests/TestCase/Command/CellCommandTest.php
=> Fix cell template filename and path

templates/bake/Command/command.twig, tests/comparisons/Command/testBakePlugin.php
=> Update bake template to remove typehint.

.stickler.yml, src/Command/EntryCommand.php, src/Command/ModelCommand.php, src/View/Helper/BakeHelper.php, src/View/Helper/DocBlockHelper.php, tests/bootstrap.php
Setting `email` as unique for all models is a bit over zealous.
=> 4.x email unique

src/Command/ModelCommand.php, src/View/Helper/BakeHelper.php, src/View/Helper/DocBlockHelper.php
https://github.com/cakephp/cakephp/pull/13943
=> 4.x - Added datetimetimezone and timestamptimezone types

src/Shell/Task/FixtureTask.php, src/Template/Bake/Element/Controller/edit.twig, src/Template/Bake/Element/Controller/index.twig, src/Template/Bake/Element/Controller/view.twig, src/View/Helper/BakeHelper.php, tests/TestCase/View/Helper/BakeHelperTest.php
To be in line with the new CS and future proof code generation (in light of easier 3.x => 4.x merges and smaller diffs).
I think we should be able to release this as minor, right?
=> Fix code to create CS valid files.

docs/en/development.rst
=> Update bake template paths

templates/bake/Template/login.twig
Refs https://github.com/cakephp/bake/issues/607
=> Remove outdated flash

composer.json, templates/bake/Model/table.twig, templates/bake/Template/index.twig, templates/bake/element/form.twig
Need WyriHaximus/TwigView#233 also to be merged and new TwigView release to be done.
=> Update templates for Twig 3 compatibility.

src/Plugin.php
Don't search plugins which have "console" hook disabled.
=> Optimize commands discovery.

src/Command/FixtureCommand.php
Need to get a timestamp value in the fixtures in order to insert records on test setup.
=> Add handling for timestampfractional field type

README.md
We have this on most package repos.
=> Add package release badge

.gitattributes, templates/bake/Form/form.twig, templates/bake/Plugin/.gitignore.twig, templates/bake/Plugin/composer.json.twig, tests/comparisons/Plugin/Company/Example/.gitignore, tests/comparisons/Plugin/Company/Example/composer.json, tests/comparisons/Plugin/SimpleExample/.gitignore, tests/comparisons/Plugin/SimpleExample/composer.json, tests/test_app/composer.json
Also - there seem to be some files missing for a baked plugin
- gitattributes
- editorconfig
=> Bake template updates

src/Command/BehaviorCommand.php, src/Command/CellCommand.php, src/Command/CommandCommand.php, src/Command/ComponentCommand.php, src/Command/ControllerCommand.php, src/Command/FixtureCommand.php, src/Command/FormCommand.php, src/Command/HelperCommand.php, src/Command/MailerCommand.php, src/Command/MiddlewareCommand.php, src/Command/ModelCommand.php, src/Command/PluginCommand.php, src/Command/ShellCommand.php, src/Command/ShellHelperCommand.php, src/Command/TaskCommand.php, src/Command/TemplateCommand.php, src/Command/TestCommand.php, src/View/BakeView.php, templates/bake/Controller/controller.twig, templates/bake/Template/add.twig, templates/bake/Template/edit.twig, tests/TestCase/Command/TemplateCommandTest.php, tests/TestCase/Utility/TemplateRendererTest.php, tests/TestCase/View/BakeViewTest.php
Use the Bake plugin prefix instead of manipulating the global paths.
=> Remove manipulation of App.paths.templates

templates/bake/element/Controller/view.twig, tests/comparisons/Controller/testBakeActions.php, tests/comparisons/Controller/testBakeActionsContent.php, tests/comparisons/Controller/testBakeWithPlugin.php
like the other views, makes it easier to set another var into it.
=> Use consistent template setting.

src/Command/AllCommand.php, src/Command/ModelCommand.php
=> Add `--prefix` option to `bake all`

tests/TestCase/Command/AllCommandTest.php
Tests for https://github.com/cakephp/bake/pull/708
=> Add tests for bake all and prefix.

src/Command/CellCommand.php, src/Command/SimpleBakeCommand.php, src/Shell/Task/SimpleBakeTask.php
I went a bit too far with the string[] ones, as they can also be nullable etc.
Instead, I now phpstan-return them as assoc arrays.
=> Use phpstan return instead.

docs/en/development.rst
lowercase bake as a folder name is ignored by the bake command
=> folder name should be CamelCase

docs/en/development.rst
Applications and themes have different paths for overrides. Refs #736
=> Correct the template override docs.

src/Command/PluginCommand.php, src/Plugin.php, src/Utility/CommonOptionsTrait.php
=> Add Common Options to Plugin Command

templates/bake/Plugin/composer.json.twig
=> Fix package version constraint being HTML encoded.

src/Command/ModelCommand.php, src/View/Helper/BakeHelper.php, tests/TestCase/Command/ModelCommandTest.php, tests/comparisons/Model/testBakeTableValidation.php
=> Update use of deprecated method.

composer.json, src/Command/ModelCommand.php, templates/bake/Plugin/phpunit.xml.dist.twig, templates/bake/Plugin/tests/bootstrap.php.twig, templates/bake/Plugin/tests/schema.sql.twig, tests/comparisons/Plugin/Company/Example/phpunit.xml.dist, tests/comparisons/Plugin/Company/Example/tests/bootstrap.php, tests/comparisons/Plugin/Company/Example/tests/schema.sql, tests/comparisons/Plugin/SimpleExample/phpunit.xml.dist, tests/comparisons/Plugin/SimpleExample/tests/bootstrap.php, tests/comparisons/Plugin/SimpleExample/tests/schema.sql
These change would go into 2.next branch to be release alongside CakePHP 4.3
=> Update plugin creation for 4.3

src/Command/ModelCommand.php, templates/bake/Model/table.twig, tests/comparisons/Model/testBakeAssociationDetectionCategoriesProductsTable.php
I ran into this error testing in master before realizing it was changed to return the first element in 2.next.
Not sure if we should just set the original array as display field.
=> Fix setting array display field
