cakephp/bake

src/Shell/Task/FixtureTask.php

When executing ```cake bake model``` empty files in Entity and Table folders are removed, but it was not the case for fixture when using ```cake bake fixture```

Delete empty file when baking fixtures

---

src/Shell/BakeShell.php
src/Template/Bake/Element/Controller/add.ctp
src/Template/Bake/Element/Controller/edit.ctp
src/Template/Bake/Element/Controller/index.ctp
src/Template/Bake/Element/Controller/view.ctp
tests/TestCase/Shell/BakeShellTest.php
tests/comparisons/Controller/testBakeActions.php
tests/comparisons/Controller/testBakeActionsContent.php
tests/comparisons/Controller/testBakeWithPlugin.php

Calling "bake" directly in the Tasks skips the $this->_getName(); function call, which separates Plugin from Name. Fix is to call main(); instead of bake();.

Fixed "all" Task to allow plugin baking.

---

src/Shell/Task/PluginTask.php
tests/TestCase/Shell/Task/PluginTaskTest.php
tests/comparisons/Plugin/testMainUpdateComposer.json

PR related to the change: https://github.com/cakephp/app/pull/206
The first commit is filtering the ROOT/plugins path from the options and exits with an error if no other path is available, I am unsure if exit; was the correct choice in a Shell Task, I would like to get some feedback regarding that.
The second commit fixed the Autoloading Generation to allow other than the default path options to be used as plugin path, the chdir adaption was required since the old version could not deal with anything but the first child of ROOT.
Any comments are appreciated.

Fixed Plugin Task to deny option of ROOT/plugins and fixed Autoloading Generation

---

src/Shell/Task/ModelTask.php
src/Template/Bake/Model/table.ctp
tests/comparisons/Model/testBakeTableConfig.php
tests/comparisons/Model/testBakeTableRelations.php
tests/comparisons/Model/testBakeTableValidation.php
tests/comparisons/Model/testBakeTableWithPlugin.php
tests/comparisons/Model/testBakeWithRules.php

Would close #32 
Please let me know if I need to change/add etc.
:)

Baked tables use App\Model\Entity\EntityName;

---

appveyor.yml
src/Shell/Task/PluginTask.php
tests/TestCase/Shell/Task/PluginTaskTest.php

- correct the composer autoloading lines generation on Windows
using 
```
bin\cake bake plugin BestPlugin
```
would generate the following in composer.json : 
```json
"BestPlugin\\": ".\\plugins\\BestPlugin/src"
```
instead of 
```json
"BestPlugin\\": "./plugins/BestPlugin/src"
```
- re-add missing functions to bake Plugins after #43

Add appveyor configuration

---

src/Template/Bake/tests/bootstrap.ctp

If plugin does not have a bootstrap file load the core tests bootstrap.

Don't assume there will always be a bootstrap file

---

src/Shell/Task/BakeTask.php

Instead of looking in stderr, the exit code of a process should be used to determine whether or not it worked.
Refs #51

Only fail subcommands when they exit non-zero.

---

src/Shell/Task/TestTask.php
tests/TestCase/Shell/Task/TestTaskTest.php

Allow running on `bin/cake bake tests <type> --all` for generating tests for all classes of the given type. Reason for using a option rather than a argument (`name == 'all'), is to prevent problems with classes called `All`.

Add ability to bake all tests for a given type

---

src/Shell/Task/TemplateTask.php
src/Utility/Model/AssociationFilter.php
src/View/Helper/BakeHelper.php
tests/TestCase/Utility/Model/AssociationFilterTest.php
tests/TestCase/View/Helper/BakeHelperTest.php

Get rid of duplicated HasMany associations already existing as BelongsToMany. Example: ArticlesTags would be removed from the list of associations used for code generation if a Articles BelongsToMany Tags association exists.

Filter HasMany associations if already exist as BelongsToMany

---

src/Shell/Task/ModelTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php

When generating validation rules, we can use the associations to exclude foreign key columns from the generated rules. These columns will already have RulesChecker rules created.
Refs #61

Exclude foriegn keys from validation rules.

---

src/Shell/Task/ModelTask.php
src/Template/Bake/Model/table.ctp
tests/TestCase/Shell/Task/ModelTaskTest.php
tests/comparisons/Model/testBakeTableConfig.php
tests/comparisons/Model/testBakeTableRelations.php
tests/comparisons/Model/testBakeTableValidation.php
tests/comparisons/Model/testBakeTableWithPlugin.php
tests/comparisons/Model/testBakeWithRules.php

Doing this fixes baking controllers, and templates that use models that connect to non-default sources.
Refs #63

Bake defaultConnectionName method for tables.

---

src/Shell/Task/ModelTask.php
tests/Fixture/CategoryThreadsFixture.php
tests/TestCase/Shell/Task/ModelTaskTest.php

If the field is not null and it is an association the join type can be inner. It gives a better performance on database.

Using inner joins when the belongs to association is mandatory

---

src/Utility/Model/AssociationFilter.php
tests/TestCase/Utility/Model/AssociationFilterTest.php

Bake shouldn't error out when an association references a table that doesn't exist. Instead that association should be filtered out.
Refs cakephp/cakephp#6270

Ignore associations that point at missing tables.

---

src/Template/Bake/tests/test_case.ctp
tests/comparisons/Test/testBakeControllerTest.php
tests/comparisons/Test/testBakePrefixControllerTest.php

Fixture lists do not need keys, and we shouldn't include them.

Don't include keys in generated fixtures.

---

src/Shell/Task/FixtureTask.php
tests/Fixture/BakeCarFixture.php
tests/TestCase/Shell/Task/FixtureTaskTest.php

Encountered a use case where I am baking fixtures for all my tables. I have a few tables where the table name is singular. This PR adds in the ability to fallback to a singular table if the plural version does not exist.

Allow for singular table names when baking fixtures

---

src/Shell/Task/TemplateTask.php

While looking into #89, I noticed that bake would silently fail if the template template was missing. This was unexpected and confusing.

Add warning when no template is rendered.

---

src/Shell/Task/FixtureTask.php
tests/TestCase/Shell/Task/FixtureTaskTest.php
tests/comparisons/Fixture/testImportRecordsFromDatabase.php

Fixtures should be generated with string datetime values, not object instances. Using strings matches the format people would normally author fixtures in. Using hydrate(false) means fixture generation will not be impacted by any virtual, hidden, or accessors on the fixtures.
Refs #97
Refs #98

Fix datetime field generation, and entity usage.

---

src/Template/Bake/Element/form.ctp
src/Template/Bake/Template/index.ctp
src/Template/Bake/Template/view.ctp
tests/comparisons/Template/testBakeEdit.ctp
tests/comparisons/Template/testBakeIndex.ctp
tests/comparisons/Template/testBakeTemplate.ctp
tests/comparisons/Template/testGetContent.ctp
tests/comparisons/Template/testGetContentAssociations.ctp
tests/comparisons/Template/testGetContentWithRoutingPrefix-add.ctp
tests/comparisons/Template/testGetContentWithRoutingPrefix-view.ctp

I think I have to update tests too...

New design generators

---

src/Template/Bake/Template/index.ctp
src/Template/Bake/Template/view.ctp
src/Utility/Model/AssociationFilter.php
tests/TestCase/Shell/Task/TemplateTaskTest.php
tests/TestCase/Utility/Model/AssociationFilterTest.php

Self associations like child categories were not showing up in the related sections. Previously these associations was filtered out entirely to clean up the navigation. This had the unfortunate side effect of eliding them from the view page as well.
This introduces a new template variable that indicates whether or not an association should be in the nav. Self-associations are marked false. This also fixes an issue where multi word self-associations would have the wrong heading.
Refs #114

Fix self associations not showing up in the related sections.

---

tests/Fixture/BakeArticlesBakeTagsFixture.php
tests/Fixture/BakeArticlesFixture.php
tests/Fixture/BakeCarFixture.php
tests/Fixture/BakeCommentsFixture.php
tests/Fixture/BakeTagsFixture.php
tests/Fixture/BinaryTestsFixture.php
tests/Fixture/CategoryThreadsFixture.php
tests/Fixture/InvitationsFixture.php
tests/TestCase/Utility/Model/AssociationFilterTest.php
tests/TestCase/View/BakeViewTest.php
tests/TestCase/View/Helper/BakeHelperTest.php

The links to the testing part of the doc blocks points to the 2.X documentation.
This points them to the 3.X documentation.

Corrects the "Tests" links in various docblocks

---

src/Shell/Task/ModelTask.php
src/Template/Bake/Model/entity.ctp
tests/TestCase/Shell/Task/ModelTaskTest.php
tests/comparisons/Model/testBakeEntityFields.php

This change avoids having to update the accessible list when new fields are added to table.
This avoids some hair pulling for new users who don't realize the entity also needs to be updated if they change table fields. I have seen newbies often struggle to figure out why their new fields are not getting saved. e.g. http://stackoverflow.com/questions/31385268/cakephp-3-new-fields-wont-save-correctly

Only set primary key fields as non-accessible.

---

src/Template/Bake/Model/table.ctp
tests/comparisons/Model/testBakeTableConfig.php
tests/comparisons/Model/testBakeTableRelations.php
tests/comparisons/Model/testBakeTableValidation.php
tests/comparisons/Model/testBakeTableWithPlugin.php
tests/comparisons/Model/testBakeWithRules.php

Closes https://github.com/cakephp/bake/issues/120

Add missing parent call for Table::initialize().

---

src/Shell/Task/FixtureTask.php
tests/Fixture/DatatypesFixture.php
tests/TestCase/Shell/Task/FixtureTaskTest.php

Add Switch case to support uuid field types in FixtureTask
Adds Unit Test by modifying the Datatypes Fixture to include a uuid test case
Verifies both that the fields uses the uuid type and that the records array
generates a regexp verified uuid field
Closes #136

Enables Fixture Task To Process Fields Of Type UUID

---

src/Shell/Task/FixtureTask.php

Instead of 10 rows, we should generate 1. This makes the fixtures
generated by `bake model` and `bake fixture` consistent.
Refs #146

Generate one row by default.

---

.travis.yml
src/Shell/Task/ControllerTask.php
src/Shell/Task/ModelTask.php
src/Shell/Task/TemplateTask.php
tests/TestCase/Shell/Task/ControllerTaskTest.php
tests/TestCase/Shell/Task/TemplateTaskTest.php

Actually the tables declared to be skipped are skipped only when bakin all models but still used when using the following command : 
```
bin/cake bake controller all
bin/cake bake template all
```
I also added the `phinxlog` table to the skipped table and also add PHP7.0 to the travis build.

fix `bake controller all` and `bake template all`

---

src/Shell/Task/TemplateTask.php

For custom bake template hooks I need the current model object.
Since it already exists it would be easy to pass it down, as well.
One could also freshly create it in the template itself, but I think this little enhancement would not hurt.

Pass object to view for custom hooks

---

src/Shell/BakeShell.php
src/Shell/Task/FixtureTask.php
src/Shell/Task/ModelTask.php
src/Shell/Task/TemplateTask.php
tests/TestCase/Shell/Task/FixtureTaskTest.php
tests/TestCase/Shell/Task/TemplateTaskTest.php

follows #149 
- fix the list generated by `bin/cake bake model`
- filter the tables to generate fixtures
- use the same table list to be skipped when using `bin/cake bake all --everything`

Fixtures generation is now using filtered table

---

src/Shell/Task/TemplateTask.php
tests/TestCase/Shell/Task/TemplateTaskTest.php
tests/test_app/App/Controller/TemplateTaskCommentsController.php

Instead of strtolower, we should use underscore() as that better matches the conventions used across the framework for template names.
Refs #156

Inflect template names.

---

.travis.yml

Skip the postgres builds for now as I'm not able to reproduce the aliasing issues we're seeing on travisci.

Attempt to get travis passing.

---

src/View/Helper/BakeHelper.php
tests/TestCase/View/Helper/BakeHelperTest.php

Make the indent-string an option to give users, who want to use their own Theme, the ability to justify the indentation, e.g. indent by tab instead of four spaces.

BakeHelper.php optionize indent string

---

src/Template/Bake/Template/view.ctp

Replaces an incorrect closing `</tr>` with a correct `</td>`.

Replace incorrect tr with td in view template

---

src/Shell/Task/TestTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php
tests/TestCase/Shell/Task/TestTaskTest.php

When baking a custom type class, tests files should only be created if the class type has been declared. Otherwise, it will lead to notices and exceptions being raised.
More details here : https://github.com/cakephp/docs/issues/3435
Linked to https://github.com/cakephp/docs/pull/3438

TestTask::bake() should be no-op if an unknown class type is being baked

---

src/Shell/Task/SimpleBakeTask.php

`bake()` and `bakeTest()` return type is a string (baked file contents), so doc tag return type should be string.

doc return tag sync with code

---

src/Template/Bake/Element/form.ctp

This PR closes #35, which was already implemented in https://github.com/cakephp/bake/commit/a14a8adb7515727d49dc0f2f797c64a03df7d1a9 which was nowhere mentioned. 
The PR removes the default attribute since thats not required anymore as implemented in https://github.com/cakephp/cakephp/pull/6559.

Remove unnecessary attribute from date inputs (Closes #35)

---

src/Template/Bake/Element/form.ctp
src/Template/Bake/Template/index.ctp
tests/Fixture/CategoryThreadsFixture.php
tests/TestCase/Shell/Task/TemplateTaskTest.php
tests/test_app/App/Model/Table/CategoryThreadsTable.php

When baking forms and list pages for tree models, we should exclude the lft/rght fields. The treebehavior manages these fields on add/update and they are not very useful on the list page.
Refs #155

Exclude lft/rght from baked output.

---

src/Shell/Task/FixtureTask.php
src/View/BakeView.php
tests/TestCase/Shell/Task/FixtureTaskTest.php
tests/comparisons/Fixture/testImportRecordsFromDatabase.php

The `import-records` option doesn't actually do anything anymore, so we don't need it. The generated import property is now correct as well.
Refs #192

Remove dead options from fixture task.

---

src/Shell/Task/ModelTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php

While it is possible to add rules for multi-column unique keys, doing so would require changing the template data, which will likely break userland templates. For that reason, I'd rather not add support for multi-column unique keys at this point in time.
Refs #182

Generate isUnique rules for single column unique key indexes.

---

src/Shell/Task/FixtureTask.php
src/Shell/Task/TestTask.php

Using TESTS constants if defined (in `config/paths.php` file), it instead of `ROOT . DS . 'tests' . DS`

Using TESTS constants if defined

---

src/Template/Bake/Element/Controller/add.ctp
src/Template/Bake/Element/Controller/edit.ctp
src/Template/Bake/Element/Controller/login.ctp
src/Template/Bake/Element/Controller/logout.ctp
tests/comparisons/Controller/testBakeActions.php
tests/comparisons/Controller/testBakeActionsContent.php
tests/comparisons/Controller/testBakeWithPlugin.php

Currently the bake doc block doesn't pass the cakephp standard, as redirect returns a response

Updated docblock returns to pass CakePHP coding standard

---

src/Shell/Task/ModelTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php
tests/comparisons/Model/testBakeEntityCustomHidden.php

Fixed baking entities with non whitelisted hidden fields, and added a test case.
`$ bin/cake bake model -f --no-table --hidden _matchingData,foo --no-test --no-fixture Examples`
Would not create a `$_hidden` field in the entity.

Allow the hidden option to work when baking entities

---

src/Shell/Task/TestTask.php
src/Template/Bake/tests/test_case.ctp
tests/TestCase/Shell/Task/TestTaskTest.php
tests/comparisons/Test/testBakeBehaviorTest.php
tests/comparisons/Test/testBakeCellTest.php
tests/comparisons/Test/testBakeComponentTest.php
tests/comparisons/Test/testBakeFixturesParam.php
tests/comparisons/Test/testBakeHelperTest.php
tests/comparisons/Test/testBakeModelTest.php
tests/comparisons/Test/testBakeShellHelperTest.php
tests/comparisons/Test/testBakeShellTest.php

This PR aims to make baked tests a little more IDE friendly by adding real properties to the baked tests.
Usually every time I bake tests, the first thing I do is adding real properties for the dynamic ones set in the generated constructor, so that I get proper code-complection, and my IDE doesn't light up like a  :christmas_tree: complaining about non-existing properties :)

Make baked tests more code-completion/inspection friendly.

---

src/Shell/Task/PluginTask.php

Very minor issue, but baking a new plugin should remove `empty` file in plugins directory if it exists.

remove empty file when baking plugin

---

README.md

License is in root file LICENSE.txt already.
Or we can remove this block alltogether as the icon above states it as well as the uppercase filename in the repo as well quite clearly.

No need to duplicate License part.

---

appveyor.yml
tests/Fixture/CategoriesFixture.php
tests/Fixture/OldProductsFixture.php
tests/Fixture/ProductVersionsFixture.php
tests/Fixture/ProductsFixture.php

as CakePHP 3.2 requires at least 5.5.9

bump min php version for appveyor

---

src/Template/Bake/Shell/shell.ctp

I always have to look this up, so figured it'd sure be handy to have it right there in the baked shell with a link to the docs.
I have run the test suite and everything passed. Let me know if you'd like me to make an attempt at including a new test case.

Add a basic OptionParser into the baked shell, for ease of customisation

---

.gitattributes

Do not exclude /src/Template/Bake/Plugin/tests/* from `git archive`.

---

src/Shell/Task/FixtureTask.php

#98 is still an issue if immutable time objects are being used (specified in `boostrap.php`).  `$value` will be an instance of `Cake\I18n\FrozenTime` instead of `DateTime`.  This change compares fields to the `DateTimeInterface` instead of the implementation `DateTime`.

Checking a field's type against interface instead of implementation.

---

src/Template/Bake/Plugin/composer.json.ctp
src/Template/Bake/Plugin/config/routes.php.ctp
tests/comparisons/Plugin/Company/Example/composer.json
tests/comparisons/Plugin/Company/Example/config/routes.php
tests/comparisons/Plugin/SimpleExample/composer.json
tests/comparisons/Plugin/SimpleExample/config/routes.php

Pinning to 3.3.* in a plugin makes upgrading a pain, as we'll need plugin authors to continuously do releases as CakePHP does new versions. Instead it is better if we set sane minimum versions and exclude backwards incompatible milestones.

Fix tests & Fix version requirements.

---

src/Shell/Task/TestTask.php
tests/TestCase/Shell/Task/TestTaskTest.php

When the controller's `modelClass` overlaps an existing public property, baking a test case would fail. We should be doing an instance check to prevent such errors. I've not used a typehint as those create fatal errors in PHP5 that we cannot catch.
Refs #254

Fix fatal error when modelClass is null

---

src/Template/Bake/Model/table.ctp

PHPStorm complains about the signature, and there indeed is the options argument missing here when baking a Table class.

Fix method signature for annotation

---

src/View/BakeView.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php
tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php
tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php
tests/comparisons/Model/testBakeTableConfig.php
tests/comparisons/Model/testBakeTableRelations.php
tests/comparisons/Model/testBakeTableValidation.php
tests/comparisons/Model/testBakeTableWithPlugin.php
tests/comparisons/Model/testBakeWithRules.php

Don't rely on errors to detect whether or not a pattern is a replacement. Also fix failing tests.
Refs cakephp/cakephp#9953

Make isRegex not rely on errors

---

src/Shell/Task/ModelTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php

This fixes a problem that happens when you already have an existing model of the same name in your app but want to bake one of the same name in your plugin. I've used as well the --table option. My main app is using an users table, now for a plugin I wanted to bake a Users model that is using the wp_users table from another DB. This was not possible without this change.
Tried this:
```sh
.\bin\cake bake model Users --table wp_fk_users -c wordpress -p Burzum/WpFrontend
```
Resulting in:
```sh
Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wordpressfk.users' doesn't exist
```

Fixing a bug that appears when trying to bake plugin models

---

src/Shell/Task/ModelTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php

Date & Time fields should how have unique validators generated, as the validator method doesn't work well on non-scalar fields.
Refs #299

Don't generate unique validators for datetime fields.

---

src/Shell/Task/BakeTemplateTask.php
src/Shell/Task/ModelTask.php
src/Shell/Task/TestTask.php

Fixed some errors which came up with phpstan.
Wrong FQDN in a docblock.
`\Cake\Console\Shell::_stop();` throws an exception, so no need to return here.
`\Bake\Shell\Task\TestTask::hasMockClass ()` only accepts one parameter.

Fix phpstan errors

---

src/View/Helper/DocBlockHelper.php

Avoid half valid output if the class or type gets passed as empty string.
Worst case, if both are empty:
```
'/**
*
*
* @var \App\View\AppView $this
*/
```
etc

Only print header if not empty.

---

src/Shell/Task/BakeTask.php
src/Shell/Task/PluginTask.php
tests/TestCase/Shell/Task/ControllerTaskTest.php
tests/TestCase/Shell/Task/PluginTaskTest.php

Make it safer to generate plugins by automatically fixing the name/namespace/directories that bake will generate.
Also update tasks that use the `--plugin` option and autocorrect camelization there as well.
Refs #351

Camelize each part of the plugin name.

---

.travis.yml
src/Shell/Task/ModelTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php
tests/comparisons/Model/testBakeEntityFullContext.php

This was removed in #134 to make adding new fields to the database easier for new developers. This created a tradeoff with more secure defaults. I'd like to re-add more secure defaults alongside warning log messages in the marshaller during debug mode to help new developers.

Reinstate accessible field generation.

---

src/Shell/Task/TestTask.php

invalid result  when using 
`bin/cake bake test Controller Users --prefix=Admin`
but when using `controller` instead of  `Controller`
returned true result

fix detect Controller name

---

src/Shell/Task/ModelTask.php

This task does not seem to exist..
My annotator tripped over it.
PS: This should actually throw an exception (3.6+?)! Loading invalid tasks and silently doing nothing sounds like a bad idea.

Remove dead task.

---

src/Shell/Task/BehaviorTask.php
src/Shell/Task/CellTask.php
src/Shell/Task/ComponentTask.php
src/Shell/Task/ControllerTask.php
src/Shell/Task/FixtureTask.php
src/Shell/Task/FormTask.php
src/Shell/Task/HelperTask.php
src/Shell/Task/MailerTask.php
src/Shell/Task/MiddlewareTask.php
src/Shell/Task/ModelTask.php
src/Shell/Task/PluginTask.php
src/Shell/Task/ShellHelperTask.php
src/Shell/Task/ShellTask.php
src/Shell/Task/TaskTask.php
src/Shell/Task/TemplateTask.php
src/Shell/Task/TestTask.php

Using the new IdeHelper feature for tasks: https://github.com/dereuromark/cakephp-ide-helper/pull/62 :
bin/cake annotations shells -v -r -p Bake

Improve IDE compatibility by providing property annotations for tasks.

---

src/Template/Bake/Template/add.ctp
src/Template/Bake/Template/edit.ctp
tests/comparisons/Template/testBakeEdit.ctp
tests/comparisons/Template/testGetContentWithRoutingPrefix-add.ctp

Forms also contain entity usage:
$this->Form->create($moduleCleanup)
The following diff is produced after "baking" and then running the [ide helper](https://github.com/dereuromark/cakephp-ide-helper/) "annotations generate":
```
/src/Template/ModuleCleanups
-> add
|   * @var \App\View\AppView $this
| + * @var \App\Model\Entity\ModuleCleanup $moduleCleanup
|   */
-> 1 annotation added.
-> edit
|   * @var \App\View\AppView $this
| + * @var \App\Model\Entity\ModuleCleanup $moduleCleanup
|   */
-> 1 annotation added.
```
With this both produce the same output - no diff anymore :)

Sync with ide-helper fixing.

---

src/Shell/BakeShell.php
src/Shell/Task/BakeTask.php
src/Utility/CommonOptionsTrait.php

This fixes a compatibility issue that will exist for all of 3.5.x so I think fixing bake is the better option. I'll also fix up the CommandScanner so this doesn't happen in the future.
Refs cakephp/cakephp#11326

Move CommonOptionsTrait.

---

src/Shell/Task/ControllerTask.php
tests/TestCase/Shell/Task/ControllerTaskTest.php

In #361 the type check was fixed which resulted in prefixed controllers having their prefixes doubled when tests were generated. By removing the code in ControllerTask tests generate correctly again.
Refs #377

Remove duplicate prefix name being applied.

---

src/Shell/Task/ModelTask.php
src/View/Helper/BakeHelper.php
tests/Fixture/BakeArticlesFixture.php
tests/Fixture/NumberTreesFixture.php
tests/TestCase/Shell/Task/ModelTaskTest.php
tests/TestCase/View/Helper/BakeHelperTest.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php
tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php
tests/comparisons/Model/testBakeTableValidation.php

#284
This pull-request depends on cakephp/cakephp/issues/11295 .

Add a maxLength rule for text columns

---

src/Shell/Task/ModelTask.php

This ensures method signature's backwards compatibility. Refs #380

Remove argument typehint.

---

src/Shell/Task/ModelTask.php

Reverts cakephp/bake#382
as I explained already to @ADmad in the comment to the original and valid change to add the typehint, the internal code expects the array, thus this revert here was invalid and a bad idea.
BC has nothing to do with this :)
See if (in_array($fieldName, $primaryKey)) { usage.

Fix array expectation via cast.

---

src/Template/Bake/Element/Controller/add.twig
src/Template/Bake/Element/Controller/edit.twig
src/Template/Bake/Element/Controller/index.twig
src/Template/Bake/Element/Controller/view.twig
tests/comparisons/Controller/testBakeActions.php
tests/comparisons/Controller/testBakeActionsContent.php
tests/comparisons/Controller/testBakeWithPlugin.php

Remove _serialize from templates

---

src/Shell/Task/ModelTask.php

When a database table contains a column that ends with "_id" by convention it is treated as a foreign key. I stumbled upon a schema where regular primary keys were named in this manner (i.e. "usr_id" was primary key of "users" table, etc.), which of course misled bake. This change introduces a check to skip such fields from being treated as associations when they are set as primary key (but only when PK is a single column).

Exclude columns of primary key from "belongsTo"

---

src/Shell/Task/TestTask.php
tests/TestCase/Shell/Task/TestTaskTest.php

A test case is generated in the incorrect namespace when the `prefix` option is specified when baking the controller.
eg:
```
bin/cake bake controller --prefix Api/Public Posts
```
I expected:
tests/TestCase/Controller/Api/Public/PostsControllerTest.php
```
<?php
namespace App\Test\TestCase\Controller\Api\Public;
```
Actually I got:
```
<?php
namespace App\Test\TestCase\Controller\Api/Public;
```

Fixes baking controller tests with prefix option

---

src/Shell/Task/TemplateTask.php
tests/TestCase/Shell/Task/TemplateTaskTest.php

Previously bake would use the `listing.twig` and created `index.ctp` when it should have used `index.twig` and created `listing.ctp` based on the help information.
This currently causes a strict error with TwigView, but I'll be opening a pull request to fix that as well.
Refs #395

Fix `bake template index listing` not generating the right file.

---

composer.json
src/Shell/BakeShell.php
src/Shell/Task/ControllerTask.php
src/Shell/Task/ModelTask.php
tests/TestCase/Shell/BakeShellTest.php

Following https://github.com/cakephp/cakephp/pull/11574 this fixes up the non interactive mode.
Currently -q would prompt for sth but you are not able to see for what. So it just endless runs.
It now properly
- uses -q (quit) as non-interactive mode and silently ignores all existent files (no accidental overwrite anymore).
- uses -f (force) to force overwrite in -q non-interactive mode as specific in help.
This should use 3.5.10 release as before it always silently overwrote the files. Thus the composer constraint.

Fix up non interactive mode using -q quit and -f force params.

---

LICENSE.txt
tests/TestCase/Shell/BakeShellTest.php
tests/TestCase/Shell/Task/FixtureTaskTest.php
tests/TestCase/TestCase.php

Start moving bake tests to use console integration tests. This is not a complete overhaul, but I wanted to update one task's tests to solicit feedback and ask for help moving other task's tests over.
The advantages I see with these tests is that they let us ensure the CLI options/API stay consistent and do what we think. Right now we have very poor coverage around options/arguments and our tests are coupled to effectively internal APIs.

RFC - Start adopting Integration tests for bake

---

src/Shell/Task/TemplateTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php
tests/TestCase/Shell/Task/SimpleBakeTaskTest.php
tests/TestCase/Shell/Task/TemplateTaskTest.php
tests/TestCase/Shell/Task/TestTaskTest.php
tests/test_app/App/Controller/AuthorsController.php
tests/test_app/App/Controller/TemplateTaskCommentsController.php
tests/test_app/App/Model/Table/AuthorsTable.php
tests/test_app/App/Model/Table/TemplateTaskCommentsTable.php

Move more tests to the integration style.
I had to move fixture files into locations that follow conventions.
I've deleted a few dead methods (bakeAction, customMethod) as they cannot be reached through the CLI interface and have no callers in `bake`. This could be construed as a breaking change but to me, the 'interface' of bake is its CLI interface and the base classes it provides. Template Task is a highly specific job of bake and isn't part of the 'public' interface.

Update more tests to use integration style

---

src/Shell/Task/CellTask.php
src/Shell/Task/TestTask.php
src/Template/Bake/View/cell.twig
tests/TestCase/Shell/Task/CellTaskTest.php

I like prefixes for code I don't want to decouple into plugin. I am missing this option in some bake tasks, currently in the cell so I have tried to add it there.
Maybe it would be good idea to implement prefix to ` src/Shell/Task/SimpleBakeTask.php` so all Tasks which extends this class can have this prefix option, but that's too much for me at the moment
Hope all OK
Reference #235

Prefix option for bake cell

---

src/Template/Bake/Model/table.twig
src/Template/Bake/tests/test_case.twig

Applications using wyrihaximus/twig-view with twig set to fail on undefined variables are unable to use these templates (table.twig, test_case.twig) without error. table.twig and test_case.twig updated to check for variables to be defined first.
Errors Produced:
> Exception: Key "value" for array with keys "description, type, name" does not exist in "/var/www/vendor/cakephp/bake/src/Template/Bake/tests/test_case.twig" at line 52. in [/var/www/vendor/twig/twig/lib/Twig/Template.php, line 556]
2018-02-09 14:54:45 Error: [Twig_Error_Runtime] Key "value" for array with keys "description, type, name" does not exist in "/var/www/vendor/cakephp/bake/src/Template/Bake/tests/test_case.twig" at line 52. in /var/www/vendor/twig/twig/lib/Twig/Template.php on line 556
> Exception: Key "extra" for …

Checking for defined variables before using them

---

src/Shell/Task/FixtureTask.php
tests/TestCase/Shell/Task/FixtureTaskTest.php

Using the table classes to read schema metadata instead of going directly to the schema information on the connection allows bake to leverage the changes made in a table class' `_initializeSchema` hook
Refs #419

Use the table class to read schema metadata

---

src/Shell/Task/FixtureTask.php
src/Template/Bake/tests/fixture.twig
tests/TestCase/Shell/Task/FixtureTaskTest.php
tests/comparisons/Fixture/testImportRecordsFromDatabase.php

This PR changes Bake fixture templates so that assignment of a fixture's records happens at run time via an `init()` method, rather than at compile time via a property declaration. The limitations imposed by the current implementation can cause problems for complex data types. See https://github.com/cakephp/bake/issues/425

Assign fixture records at run time rather than compile time

---

src/Shell/Task/PluginTask.php
src/Template/Bake/Plugin/src/Plugin.php.twig
tests/comparisons/Plugin/Company/Example/src/Plugin.php
tests/comparisons/Plugin/SimpleExample/src/Plugin.php

Create the stub plugin class when creating a new plugin. I needed to fix the template name mangling to ensure that Plugin.php is generated correctly.

Add plugin class creation when baking a plugin.

---

src/Shell/Task/FixtureTask.php

Error Location:  Shell/Task/FixtureTask.php, line: 276
bake version 1.7.0

TableSchema::index() is deprecated. Use TableSchema::getIndex() instead.

---

src/Shell/Task/CommandTask.php
src/Shell/Task/TestTask.php
src/Template/Bake/Command/command.twig
src/Template/Bake/tests/test_case.twig
tests/TestCase/Shell/BakeShellTest.php
tests/TestCase/Shell/Task/CommandTaskTest.php
tests/TestCase/Shell/Task/TestTaskTest.php
tests/comparisons/Command/testBake.php
tests/comparisons/Command/testBakePlugin.php
tests/comparisons/Test/testBakeCommandTest.php

Make it possible to bake a Command class.
`bake command Example`

Add support for baking a Command Class

---

src/Template/Bake/tests/test_case.twig
tests/comparisons/Test/testBakeCommandTest.php

Now that bake task generate below code:
```php
public function setUp()
{
parent::setUp();
$this->$this->useCommandRunner();
}
```
As `TestTake` provide _construct_ value with **$this**:
```
$construct = "\$this->useCommandRunner();";
```
Theres no reason to repeat **$this** here.

Fix CommandTest setup

---

composer.json
src/Shell/Task/FixtureTask.php
tests/Fixture/BinaryTestsFixture.php
tests/TestCase/Shell/Task/FixtureTaskTest.php

Depends on cakephp/cakephp/pull/12518, https://github.com/cakephp/cakephp/pull/12552 & https://github.com/cakephp/cakephp/pull/12622
When text field is 1 charcter long generated dummy text in a fixture does not fit into a database resulting in the following error:
```
Exception: Unable to insert fixture "App\Test\Fixture\ExampleFixture" in "App\Test\TestCase\Controller\ExampleControllerTest" test
case:
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'value' at row 1 in [.../vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 345]
```

Fixed dummy text generation for short text fields

---

.travis.yml
src/Shell/Task/ControllerTask.php

Closes #471
I've looked into history, and the variable was used last back in 2014, when admin views, and admin routing were features baked. Currently the mentioned variable is not used anywhere in the cakephp/bake codebase, which means, it's safe to remove
patch tested in environment mentioned in #471

PHP7.3 removed warning about undefined variable admin

---

src/Command/BakeCommand.php
src/Command/SimpleBakeCommand.php
src/Command/TestCommand.php
src/Plugin.php
src/Shell/BakeShell.php
src/Shell/Task/BakeTask.php
src/Shell/Task/FixtureTask.php.orig
src/Shell/Task/PluginTask.php
src/Shell/Task/TestTask.php
src/Utility/CommonOptionsTrait.php
tests/TestCase/Command/TestCommandTest.php
tests/TestCase/Shell/BakeShellTest.php
tests/TestCase/Shell/Task/TestTaskTest.php
tests/bootstrap.php
tests/comparisons/Test/testBakeBehaviorTest.php
tests/comparisons/Test/testBakeCellTest.php
tests/comparisons/Test/testBakeCommandTest.php
tests/comparisons/Test/testBakeFixturesParam.php
tests/comparisons/Test/testBakeHelperTest.php
tests/comparisons/Test/testBakeModelTest.php
tests/comparisons/Test/testBakeNoFixtureParam.php
tests/comparisons/Test/testBakeShellHelperTest.php
tests/comparisons/Test/testBakeShellTaskTest.php
tests/comparisons/Test/testBakeShellTest.php
tests/test_app/App/Application.php

The first of many changes to bake moving subcommands to be Command classes instead of Shell classes. I started with TestTask as it is used by all other tasks.
I've not removed `TestTask` as it is still in use by all the other tasks and I didn't want to deal with all the failing tests.

4.x Move test task to a command.

---

src/Command/BakeCommand.php
src/Command/CellCommand.php
src/Command/SimpleBakeCommand.php
src/Command/TestCommand.php
src/Plugin.php
src/Utility/CommonOptionsTrait.php
src/Utility/TemplateRenderer.php
templates/bake/View/cell.twig
tests/TestCase/Command/CellCommandTest.php
tests/TestCase/Shell/BakeShellTest.php
tests/TestCase/TestCase.php
tests/bootstrap.php
tests/comparisons/Cell/testBakePlugin.php

Move the first of the `SimpleBakeTask` subclasses over to a command. This should make converting the other subclasses easier as they are mostly the same.

4.x Convert CellTask to a Command

---

phpstan.neon
src/Utility/SubsetSchemaCollection.php

The new interface was partly added to make this scenario easier. Use the interface instead of the base class.

Switch to using the interface instead of extend

---

src/Plugin.php
tests/TestCase/PluginTest.php
tests/test_app/App/Command/CustomControllerCommand.php
tests/test_app/Plugin/BakeTest/src/Command/ZerglingCommand.php

Bake will now auto-discover bake commands and attach them to the command collection using a strict set of naming conventions.
* Command names are the underscored version of their class name.
* If a command has an All suffix it will be converted into an ` all`   subcommand
* Abstract classes and interfaces are not included.

4.x - Command discovery

---

templates/bake/Template/index.twig
tests/comparisons/Template/testBakeIndex.php
tests/comparisons/Template/testBakeIndexWithIndexLimit.php

`Paginator::counter` expects a `string` as it's first parameter since 4.x

Fix paginator counter

---

src/Shell/Task/BakeTask.php
src/Template/Bake/tests/fixture.twig
src/Utility/Model/AssociationFilter.php
src/View/Helper/DocBlockHelper.php
tests/Fixture/BakeArticlesBakeTagsFixture.php
tests/Fixture/BakeArticlesFixture.php
tests/Fixture/BakeCarFixture.php
tests/Fixture/BakeCommentsFixture.php
tests/Fixture/BakeTagsFixture.php
tests/Fixture/CategoriesFixture.php
tests/Fixture/CategoriesProductsFixture.php
tests/Fixture/InvitationsFixture.php
tests/Fixture/OldProductsFixture.php
tests/Fixture/ProductVersionsFixture.php
tests/Fixture/ProductsFixture.php
tests/TestCase/PluginTest.php
tests/TestCase/Shell/Task/ControllerTaskTest.php
tests/TestCase/Shell/Task/FixtureTaskTest.php
tests/TestCase/Shell/Task/TestTaskTest.php
tests/TestCase/Utility/Model/AssociationFilterTest.php
tests/TestCase/View/BakeViewTest.php
tests/TestCase/View/Helper/BakeHelperTest.php
tests/comparisons/BakeTemplate/testGenerateWithTemplateFallbacks.ctp
tests/comparisons/Fixture/testImportRecordsFromDatabase.php
tests/comparisons/Model/testBakeEntityFieldsDefaults.php

I know I'm a nitpicker but I always found the empty line in the class doc blocks superfluous.
Finally fixed that.
Before:
```` php
/**
* Foo class
*
*/
````
Now:
```` php
/**
* Foo class
*/
````

Remove empty line in class doc blocks

---

src/View/Helper/DocBlockHelper.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesTableSigned.php
tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionOldProductsTableSigned.php
tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php
tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTableSigned.php
tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionProductsTableSigned.php
tests/comparisons/Model/testBakeEntityWithPlugin.php
tests/comparisons/Model/testBakeTableConfig.php
tests/comparisons/Model/testBakeTableRelations.php
tests/comparisons/Model/testBakeTableValidation.php
tests/comparisons/Model/testBakeTableWithPlugin.php
tests/comparisons/Model/testBakeWithRules.php
tests/comparisons/Model/testGetBehaviors.php

There is a reason why it is called "orFail"...
https://api.cakephp.org/3.7/class-Cake.ORM.Table.html#_saveOrFail

Correct return value type hint annotations for Table::saveOrFail()

---

src/Shell/Task/TemplateTask.php
src/Utility/TemplateRenderer.php
tests/TestCase/Command/TemplateCommandTest.php

The default template sets do not include a template for delete. We shouldn't emit errors when that template is absent. This restores behavior consistency with 3.x which also used verbose output.

Don't output to stderr when templates are missing

---

src/View/Helper/BakeHelper.php
tests/TestCase/View/Helper/BakeHelperTest.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesTableSigned.php
tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTable.php
tests/comparisons/Model/testBakeAssociationDetectionProductVersionsTableSigned.php
tests/comparisons/Model/testBakeEntityCustomHidden.php
tests/comparisons/Model/testBakeEntityFieldsDefaults.php
tests/comparisons/Model/testBakeEntityFieldsWhiteList.php
tests/comparisons/Model/testBakeEntityFullContext.php
tests/comparisons/Model/testBakeEntityHidden.php
tests/comparisons/Model/testBakeEntityWithPlugin.php
tests/comparisons/Model/testBakeTableConfig.php
tests/comparisons/Model/testBakeTableWithCounterCache.php
tests/comparisons/Model/testBakeTableWithPlugin.php
tests/comparisons/Model/testBakeWithRulesUnique.php
tests/comparisons/Test/testBakeControllerTest.php
tests/comparisons/Test/testBakeFixturesParam.php
tests/comparisons/Test/testBakeModelTest.php
tests/comparisons/Test/testBakePrefixControllerTest.php
tests/comparisons/Test/testBakePrefixControllerTestWithCliOption.php

Right now the code generated by bake does not pass codesniffer:dev-next which is what will be the 4.x version of our codesniffer rules.

4.x Add trailing commas to generated code

---

src/Shell/Task/ModelTask.php
tests/TestCase/Shell/Task/ModelTaskTest.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesTable.php
tests/comparisons/Model/testBakeAssociationDetectionCategoriesTableSigned.php
tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionOldProductsTableSigned.php
tests/comparisons/Model/testBakeAssociationDetectionProductsTable.php
tests/comparisons/Model/testBakeAssociationDetectionProductsTableSigned.php

#531 
Added `$metaData['default'] === false` too in case other drivers use this and for future-proofing to what I hope would be future behaviour. Would make more sense for TableSchema to be setting `['default']` to `false` rather than `null` (and use `null` when the column default is actually `NULL`).

Stop baking requirePresence validation when db default set

---

src/Command/ControllerAllCommand.php
src/Command/ControllerCommand.php
src/Command/EntryCommand.php
src/Command/FixtureCommand.php
src/Command/ModelAllCommand.php
src/Command/ModelCommand.php
src/Command/TemplateCommand.php
templates/bake/Command/command.twig
tests/TestCase/Command/EntryCommandTest.php
tests/bootstrap.php
tests/comparisons/Command/testBakePlugin.php

Refs: https://github.com/cakephp/cakephp/pull/13194
output:
```
Current Paths:
* app:  src
* root: ...bake
* core: ...bake/vendor/cakephp/cakephp
Available Commands:
App:
- bake command
- bake shell
- bake shell_helper
Bake:
- bake all
- bake behavior
- bake cell
- bake component
- bake controller
- bake controller all
- bake fixture
- bake fixture all
- bake form
- bake helper
- bake mailer
- bake middleware
- bake model
- bake model all
- bake plugin
- bake task
- bake template
- bake template all
- bake test
To run a command, type `cake command_name [args|options]`
To get help on a specific command, type `cake command_name --help`
```
@markstory how we can move bellow lists to `bake` section?
```
App:
- bake command
- bake shell
- bake shell_helper
```
also description does not show …

4.x remove subcommand

---

src/View/BakeView.php

You had to manually delete the `tmp/cache/twigView` folder every time you alter your bake templates to see the correct results. Fixes  #549

Disable the twig view caching

---

src/Command/TemplateCommand.php
tests/TestCase/Command/TemplateCommandTest.php

I have made a start on trying to [reduce the amount of noise](https://i.imgur.com/qtpM2ar.png) generated by an error when baking templates.
It seems that when the `getPrimaryKey()` method is called, this causes a chain reaction, because the schema doesn't exist etc.
I'm open to suggestions to improve the Exception handling, as I can see some instances where a stack trace might be helpful. Perhaps the error could be logged instead?
Thoughts welcome and I can update the pull request. 
Thanks!

Resolve #554 Do not output a full stack trace for a missing table

---

src/Shell/Task/BakeTask.php
src/Shell/Task/SimpleBakeTask.php

Tested on linux - PHP 7.2.13
Error: Return value of Bake\Shell\Task\SimpleBakeTask::main() must be of the type integer or null, none returned

Fixed return type issue

---

src/Template/Bake/Plugin/tests/bootstrap.php.twig
tests/comparisons/Plugin/Company/Example/tests/bootstrap.php
tests/comparisons/Plugin/SimpleExample/tests/bootstrap.php

The fix done in #560 addressed issues for when a plugin didn't have a config/bootstrap.php but not when that file was missing. These changes work in both scenarios, and include a comment on how to customize configuration if necessary.

Fix plugin bootstrap setup

---

phpstan.neon
src/Command/PluginCommand.php
tests/TestCase/Command/PluginCommandTest.php
tests/TestCase/Utility/TemplateRendererTest.php

CakePHP will soon be getting a new PluginLoadCommand. This allows forwards/backwards compatibility during the beta release cycles.

Add forwards compatible plugin loading.

---

docs.Dockerfile
docs/config/all.py

Add the bake 2.x docs to the generate docs image for bake. Both versions will only update when master is updated right now. I think this is OK as once 2.x becomes master I don't foresee us needing many quick docs fixes to the 1.x version of bake.

Publish 2x docs

---

phpstan.neon
src/Command/PluginCommand.php

It has been removed from cakephp/core and we've done a beta since it was removed. This shim should no longer be necessary.

Remove PluginShell reference

---

src/Command/FixtureCommand.php
src/Command/ModelCommand.php
src/Command/PluginCommand.php
src/Command/SimpleBakeCommand.php
src/Command/TestCommand.php
src/Shell/Task/SimpleBakeTask.php

After baking certain templates, a directory file placeholder is removed as it is replaced by the baked files. In `cakephp/app:4.x`, this file has changed from `empty` to `.gitkeep`.
This PR reflects that change.
https://github.com/cakephp/app/commit/024b74e343fe81ee4f7a0e404ce4df63d1168dc3

Replace deleting directory placeholder file from 'empty' to '.gitkeep' when baking templates

---

src/Command/MailerCommand.php
tests/TestCase/Command/MailerCommandTest.php

They serve no purpose. Closes #625.

Remove creation of empty email layouts by mailer command.

---

src/Command/BakeCommand.php

Using this classname causes analysis fails in other packages.

Don't use the old class name.

---

templates/bake/Plugin/src/Plugin.php.twig
tests/comparisons/Plugin/Company/Example/src/Plugin.php
tests/comparisons/Plugin/SimpleExample/src/Plugin.php

Including the parent calls can lead to less surprising outcomes when users follow tutorials or examples.
Fixes cakephp/cakephp#14052

Include parent call in generated plugin class methods

---

src/Command/SimpleBakeCommand.php

some bake classes could have not `name` in their argument list
this prevents from error when first argument passes anonymously
Refs : https://github.com/cakephp/migrations/pull/425#discussion_r369862861

use `getArgumentAt()` instead of `getArgument()`

---

templates/bake/element/Controller/add.twig
templates/bake/element/Controller/delete.twig
templates/bake/element/Controller/edit.twig
templates/bake/element/Controller/index.twig
templates/bake/element/Controller/login.twig
templates/bake/element/Controller/logout.twig
templates/bake/element/Controller/view.twig
tests/comparisons/Controller/testBakeActions.php
tests/comparisons/Controller/testBakeActionsContent.php
tests/comparisons/Controller/testBakeActionsOption.php
tests/comparisons/Controller/testBakeWithPlugin.php

We should be documenting return Response|null|void to avoid false positives with PHPStan. See https://github.com/phpstan/phpstan/issues/2643
When baking a new Controller on a table and then running PHPStan 0.12.14 the following errors are found.
```
------ ----------------------------------------------------------------- 
Line   Controller/TestBakeController.php                                
------ ----------------------------------------------------------------- 
27     Method App\Controller\TestBakeController::index() should return  
Cake\Http\Response|null but return statement is missing.         
43     Method App\Controller\TestBakeController::view() should return   
Cake\Http\Response|null but return statement is missing.         
67     Method …
```

Correcting Controller Docblocks

---

src/Command/CellCommand.php
src/Command/ControllerCommand.php
src/Command/FixtureCommand.php
src/Command/ModelCommand.php
src/Command/PluginCommand.php
src/Command/SimpleBakeCommand.php
src/Command/TemplateCommand.php
src/Command/TestCommand.php
tests/TestCase/Command/AllCommandTest.php
tests/TestCase/Command/CellCommandTest.php
tests/TestCase/Command/CommandCommandTest.php
tests/TestCase/Command/ControllerAllCommandTest.php
tests/TestCase/Command/ControllerCommandTest.php
tests/TestCase/Command/EntryCommandTest.php
tests/TestCase/Command/FixtureAllCommandTest.php
tests/TestCase/Command/MailerCommandTest.php
tests/TestCase/Command/MiddlewareCommandTest.php
tests/TestCase/Command/ModelAllCommandTest.php
tests/TestCase/Command/ModelCommandAssociationDetectionTest.php
tests/TestCase/Command/ModelCommandTest.php
tests/TestCase/Command/PluginCommandTest.php
tests/TestCase/Command/SimpleBakeCommandTest.php
tests/TestCase/Command/TaskCommandTest.php
tests/TestCase/Command/TemplateAllCommandTest.php
tests/TestCase/Command/TemplateCommandTest.php
tests/TestCase/Command/TestCommandTest.php

This will allow the `--force` option to be applied to commands. I've also updated the the various tests to not use the deprecated Command namespace.
Fixes #655

Pass the force option into createFile() calls.

---

templates/bake/tests/fixture.twig
tests/Fixture/CategoriesFixture.php
tests/Fixture/CategoriesProductsFixture.php
tests/Fixture/OldProductsFixture.php
tests/Fixture/ProductVersionsFixture.php
tests/Fixture/ProductsFixture.php
tests/bootstrap.php

I fixed it because it is deprecated syntax.
```
@codingStandardsIgnoreStart → phpcs:disable
@codingStandardsIgnoreEnd → phpcs:enable
@codingStandardsIgnoreFile → phpcs:ignoreFile
```
`@codingStandardsIgnoreLine` is also deprecated, but not used in this repository.
ref. https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file
> Note: Before PHP_CodeSniffer version 3.2.0, use // @codingStandardsIgnoreStart instead of // phpcs:disable, and use // @codingStandardsIgnoreEnd instead of // phpcs:enable. The @codingStandards syntax is deprecated and will be removed in PHP_CodeSniffer version 4.0.

@codingStandards syntax is deprecated

---

src/Command/TestCommand.php
templates/bake/tests/test_case.twig
tests/TestCase/Command/TestCommandTest.php
tests/comparisons/Test/testBakeBehaviorTest.php
tests/comparisons/Test/testBakeCellTest.php
tests/comparisons/Test/testBakeCommandTest.php
tests/comparisons/Test/testBakeControllerTest.php
tests/comparisons/Test/testBakeFixturesParam.php
tests/comparisons/Test/testBakeHelperTest.php
tests/comparisons/Test/testBakeModelTest.php
tests/comparisons/Test/testBakeNoFixtureParam.php
tests/comparisons/Test/testBakeShellHelperTest.php
tests/comparisons/Test/testBakeShellTaskTest.php
tests/comparisons/Test/testBakeShellTest.php

Resolves https://github.com/cakephp/bake/issues/658
I do have a weird thing showing up now though:
```
+\n
+    /**\n
+     * Test initial setup\n
+     *\n
+     * @return void\n
+     */\n
+    public function testInitialization(): void\n
+    {\n
+        $this->markTestIncomplete('Not implemented yet.');\n
+    }\n
}\n
```
Where does this one now come from?

Remove not needed testInitialize test

---

src/Command/TestCommand.php
tests/TestCase/Command/TestCommandTest.php
tests/comparisons/Test/testBakeControllerWithoutModelTest.php
tests/test_app/App/Controller/NoModelController.php

A controller with
```php
/**
* @var string
*/
protected $modelClass = '';
```
and
```
cake bake test Controller ServiceExamplesController -p Sandbox
```
leads to
```
Exception: Default modelClass is empty
In [/home/vagrant/Apps/sandbox.local/vendor/cakephp/cakephp/src/Datasource/ModelAwareTrait.php, line 98]
2020-03-16 16:59:47 Error: [UnexpectedValueException] Default modelClass is empty in /home/vagrant/Apps/sandbox.local/vendor/cakephp/cakephp/src/Datasource/ModelAwareTrait.php on line 98
Stack Trace:
- /home/vagrant/Apps/sandbox.local/vendor/cakephp/bake/src/Command/TestCommand.php:482
- /home/vagrant/Apps/sandbox.local/vendor/cakephp/bake/src/Command/TestCommand.php:440
- /home/vagrant/Apps/sandbox.local/vendor/cakephp/bake/src/Command/TestCommand.php:246
- …
```

Fix baking controller tests without models.

---

composer.json
src/Command/ControllerCommand.php
templates/bake/Controller/controller.twig
tests/TestCase/Command/ControllerCommandTest.php
tests/test_app/Plugin/Company/Pastry/src/Controller/AppController.php

When creating controllers for plugins if there is a plugin AppController we should use it instead of the application's AppController.

Use plugin AppController if present

---

.travis.yml
composer.json
phpstan.neon
src/Command/AllCommand.php
src/Command/ControllerAllCommand.php
src/Command/ControllerCommand.php
src/Command/EntryCommand.php
src/Command/FixtureAllCommand.php
src/Command/FixtureCommand.php
src/Command/ModelAllCommand.php
src/Command/ModelCommand.php
src/Command/PluginCommand.php
src/Command/SimpleBakeCommand.php
src/Command/TemplateAllCommand.php
src/Command/TemplateCommand.php
src/Command/TestCommand.php
src/Shell/Task/BakeTask.php
tests/comparisons/Command/testBake.php

```
bin/cake bake migration_snapshot
```
throws
> Exception: Return value of Bake\Command\EntryCommand::execute() must be of the type int or null, bool returned
In [/sandbox.local/vendor/cakephp/bake/src/Command/EntryCommand.php, line 130]
As the Shell return value is still
@return int|bool|null
So this fixes it
Also fixed phpstan level to 5, as everything below is not a good quality.
Did some minor cleanup along the way.
I don't think anyone is extending the public methods of those classes.
But we can make this a minor if needed.

Fix exception. Cleanup.

---

src/Utility/TableScanner.php
tests/TestCase/Command/AllCommandTest.php
tests/TestCase/Command/ControllerAllCommandTest.php
tests/TestCase/Command/ControllerCommandTest.php
tests/TestCase/Command/FixtureAllCommandTest.php
tests/TestCase/Command/FixtureCommandTest.php
tests/TestCase/Command/ModelAllCommandTest.php
tests/TestCase/Command/ModelCommandAssociationDetectionTest.php
tests/TestCase/Command/ModelCommandTest.php
tests/TestCase/Command/TemplateAllCommandTest.php
tests/TestCase/Command/TemplateCommandTest.php
tests/TestCase/Command/TestCommandTest.php
tests/TestCase/Utility/Model/AssociationFilterTest.php
tests/TestCase/Utility/TableScannerTest.php
tests/TestCase/Utility/TemplateRendererTest.php
tests/TestCase/View/Helper/BakeHelperTest.php

I need the TableScanner for the IDE plugin, and I found that having multiple plugins with their own phinxlog is cumbersome to exclude them properly.
People should be able to pass also a regex pattern. If `/` is detected it will use regexp matching.
Also: Isn't `cake_sessions` `sessions` nowadays by default? I added that one as well.

Allow regex pattern for ignore

---

composer.json

Only the app needs cakephp/plugin-installer as dependency.

Plugins don't need plugin-installer as dependency

---

src/Utility/CommonOptionsTrait.php

Fixes issue #674 - look in templates/bake rather than src/Template/Bake when collecting the list of available themes to use when baking.

Use correct path for --theme option with bake

---

templates/bake/Form/form.twig

According to the Modelless Forms documentation, the validationDefault method must be used to get an instance of Cake\Validation\Validator

Incorrect method _buildValidator rendered when baking modelless form

---

src/Command/AllCommand.php

- Having the list of commands as a protected property allows it to be modified without needing to override the execute method.
- This allows one to change the scope of the Commands called also, e.g. for plugins.
- I've also flipped the foreach loop in the execute method for performance (i.e. to avoid an extra loop).

Make the list of commands run by AllCommands a property

---

docs/en/development.rst
src/View/BakeView.php
tests/TestCase/View/BakeViewTest.php
tests/test_app/templates/plugin/Bake/override.twig

The changes in #680 broke compatibility and changed the documented paths that bake would use. I'm reluctant to add another break and go back to what it was as I think the changes to use CakePHP's conventions were generally good ones. This change updates the documentation and removes the `Bake/bake` path from application overrides.
Fixes #698

Fix template override paths

---

src/View/Helper/DocBlockHelper.php
tests/comparisons/Model/testBakeEntityWithPropertyTypeHints.php

Prior to this fix if a table column was mapped to a custom database type class
the `@property` annotation generated for the field in entity class did not
have a type specified.

Default to PHP type `string` for unknown/custom database types.

---

src/Command/FixtureCommand.php

With PostgreSQL and timestamptimezone field type you get empty '' record values in fixtures and because of that running phpunit tests fails in some cases.

added timestamptimezone field type

---

composer.json
src/Plugin.php
tests/TestCase/PluginTest.php
tests/test_app/Plugin/WithBakeSubFolder/src/Command/Bake/LedZepplinCommand.php
tests/test_app/Plugin/WithBakeSubFolder/src/Command/TheWhoCommand.php

If this subfolder exists, bake plugin will only use commands under that
directory as bake commands by default and will not check the command
files directly under "Command" folder.

Allow using "Command/Bake" subfolder for bake commands.

---

src/Command/ModelCommand.php

We don't need to hard-code the warning wrapper.

Log using warning()

---

templates/bake/Plugin/composer.json.twig
tests/comparisons/Plugin/Company/Example/composer.json
tests/comparisons/Plugin/SimpleExample/composer.json

This matches the current phpunit version constraint of `cakephp/cakephp`.

Update version constraint for phpunit in baked composer.json

---

composer.json
src/Command/ModelCommand.php
src/View/Helper/BakeHelper.php
templates/bake/Controller/controller.twig
templates/bake/Model/entity.twig
templates/bake/Model/table.twig
templates/bake/element/Controller/edit.twig
templates/bake/element/Controller/index.twig
templates/bake/element/Controller/view.twig
templates/bake/element/array_property.twig
templates/bake/tests/test_case.twig

The existing `BakeHelper::stringifyList()` is very simplistic
and only supports an array of strings, which requires crafting
config arrays in a specific way which is quite cumbersome.

Add new helper method for exporting vars.

---

tests/TestCase/Command/ModelCommandTest.php
tests/comparisons/Model/testBakeTableValidation.php

This test was lost when bake tasks were converted to commands for CakePHP 4.x.
Without the `ModelCommandTest::testBakeTableValidation()` test the comparison file
`testBakeTableValidation.php` was unused.

Add model validation generation test.

---

templates/bake/tests/test_case.twig
tests/TestCase/Command/AllCommandTest.php
tests/TestCase/Command/CommandCommandTest.php
tests/TestCase/Command/TestCommandTest.php
tests/comparisons/Test/testBakeComponentTest.php
tests/comparisons/Test/testBakeControllerTest.php
tests/comparisons/Test/testBakeControllerWithoutModelTest.php
tests/comparisons/Test/testBakeModelTest.php
tests/comparisons/Test/testBakePrefixControllerTest.php
tests/comparisons/Test/testBakePrefixControllerTestWithCliOption.php

This PR adds `@uses` annotations to test methods to indicate which method is being tested, and makes navigation to the code being tested easier. This is especially useful for ORM `find` methods, Command `execute` method and controller actions.
Example of the `index` action on `PostsController`:
```php
/**
* Test index method
*
* @return void
* @uses \Bake\Test\App\Controller\PostsController::index()
*/
public function testIndex(): void
{
$this->markTestIncomplete('Not implemented yet.');
}
```
Solves #755

Add `@uses` annotation to method level tests.

---

templates/bake/Template/add.twig
templates/bake/Template/edit.twig
tests/TestCase/Command/TemplateCommandTest.php
tests/comparisons/Template/testBakeEdit.php
tests/comparisons/Template/testBakeEditWithBelongsToManyAssociation.php

Adds proper docblock variables for associations in `add` and `edit`templates.
See #759

Add association variables to add and edit templates

---

templates/bake/Template/add.twig
templates/bake/Template/edit.twig
tests/comparisons/Template/testBakeEdit.php
tests/comparisons/Template/testBakeEditWithBelongsToManyAssociation.php

See conversation #761.
This PR adds a more specific typehint to association variables in the `add` and `edit` templates.
While @othercorey suggested `\Cake\Collection\CollectionInterface|string[]`, I used `string[]|\Cake\Collection\CollectionInterface` as to match the order used in `index` template.

Add more specific docblock typehinting for `add` and `edit` templates

---

src/Command/CommandHelperCommand.php
src/Command/TestCommand.php
templates/bake/Command/helper.twig
tests/TestCase/Command/CommandHelperTest.php
tests/comparisons/Command/testBakeCommandHelper.php
tests/comparisons/Command/testBakeCommandHelperPlugin.php
tests/comparisons/Test/testBakeCommandHelperTest.php

This PR adds a command to bake `CommandHelper` classes.
See #633

Add `CommandHelper` bake command
